matrix:
  include:
    - language: node_js
      #sudo: required
      node_js: 8
      env: 
        - NAME="Node 8"
      install:
        #- sudo apt-get install build-essential g++ make -y
        - npm cache verify
        - npm install
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sleep 3 # give xvfb some time to start
      script:
        - npm --versions
        - npm run build
        - npm test
