build: off
image: Visual Studio 2019

platform:
  - x64

branches:
  only:
    - master

skip_tags: true

environment:
  nodejs_version: '12'

#cache:
#  - node_modules -> package.json

install:
  - ps: Install-Product node $env:nodejs_version
  - npm ci
  - npm run build

test_script:
  - node --version
  - npm test
